export const translations = {
  en: {
    // Home page
    homeEyebrow: "HOME",
    homeWelcome: "Ready to LARP?",
    homeStartIntake: "START",

    // Language switcher
    languageLabel: "Language",
    languageEnglish: "English",
    languageSpanish: "Español",

    // Telemetry banner
    telemetryAcronym: "Learn, Apply, Reflect, Progress",

    // Stepper
    stepperPickTarget: "Pick a target",
    stepperMapWhatYouHave: "Map what you have",
    stepperYourWeek: "Your week",

    // Step 1 — role
    step1Eyebrow: "Step 01 / Target",
    step1Heading: "Pick a direction — you can always change it.",
    step1Subheading:
      "Pick one. You don't have to be sure — we just need somewhere to start.",
    step1FreeTextLabel: "Or describe it in your own words",
    step1FreeTextPlaceholder: "e.g. something where I get paid to write or research",
    step1NoneFitButton: "None of these fit — let me describe it",
    step1Continue: "Continue →",

    // Step 2 — skills
    step2Eyebrow: "Step 02 / Inputs",
    step2Heading: "What have you done so far?",
    step2Subheading:
      "Tap anything that's true. Nothing yet is a real answer — first quarter is allowed to be empty.",
    step2Back: "← Back",
    step2GeneratePlan: "Generate plan →",
    quickContextLabel: "Anything that describes you?",
    contextLabel: "Anything else worth knowing?",
    contextPlaceholder:
      "Optional. e.g. 'I'm a transfer student' or 'I already have an internship lined up but want a stretch role'",
    chipSwitchingMajors: "I'm switching majors",
    chipTransfer: "I'm a transfer student",
    chipFirstGen: "I'm first-gen",
    chipWorkingPartTime: "I'm working part-time",

    // Skill group labels
    skillGroupCoding: "Coding",
    skillGroupDataAnalysis: "Data & analysis",
    skillGroupDesignCreative: "Design & creative",
    skillGroupResearchLab: "Research & lab",
    skillGroupLeadershipCommunity: "Leadership & community",
    skillGroupWorkMoney: "Work & money",
    skillGroupToolsMisc: "Tools & misc",
    skillGroupHonestAnswers: "Honest answers",

    // Loading state
    loading1: "Reading the role…",
    loading2: "Mapping what you have…",
    loading3: "Picking campus moves with the highest leverage…",
    loading4: "Writing your week…",

    // Plan card
    planEyebrow: "This week — your plan",
    planStartOver: "← Start over",
    planPrint: "Print",
    planGap: "Gap",
    planSkill: "Skill",
    planUnlocks: "Unlocks",
    planDoThisWeek: "Do this week →",
    planFooterPrefix: "Generated by L.A.R.P. with",

    // Resource type labels
    resourceTypeClub: "Club",
    resourceTypeResearch: "Research",
    resourceTypeWorkshop: "Workshop",
    resourceTypeInternshipLite: "Internship-lite",
    resourceTypeIncubator: "Incubator",
    resourceTypeProgram: "Program",

    // Dashboard placeholder
    dashboardEyebrow: "Dashboard placeholder",
    dashboardHeadingPrefix: "After onboarding:",
    dashboardSubheading:
      "Temporary landing area for the dashboard your teammate is building: skills, resume builder, campus locations, and saved next steps.",
    dashboardReplaceMe: "Replace me",
    dashboardSkillsSnapshot: "Skills Snapshot",
    dashboardResumeBuilder: "Resume Builder",
    dashboardResumeBuilderDescription:
      "Placeholder for generated bullets and editable LaTeX export.",
    dashboardLocations: "Locations",
    dashboardNextSteps: "Next Steps",

    // Dashboard
    dashboardSectionEyebrow: "Dashboard",
    dashboardTopIndustrySkills: "Top skills in industry",
    dashboardSkillsRadarNeed: "Needed",
    dashboardSkillsRadarHave: "You",
    dashboardResumeInputs: "Resume inputs",
    dashboardNoChipsSelected:
      "No chips selected yet. The resume builder will still give you a starter template.",

    // Resume builder
    resumeBuilderEyebrow: "Resume builder",
    resumeBuilderTitle: "Jake's Resume Template, prefilled",
    resumeBuilderDescription:
      "Paste a job description and any completed project notes, then click Go to rewrite the resume keywords. The preview shows the PDF as an employer would see it, and the LaTeX can be copied into Overleaf for easy editing.",
    resumeBuilderCopyLatex: "Copy LaTeX",
    resumeBuilderCopied: "Copied",
    resumeBuilderDownloadPdf: "Download PDF",
    resumeBuilderBuildingPdf: "Building PDF",
    resumeBuilderJobDescriptionLabel: "Intended job description",
    resumeBuilderJobDescriptionPlaceholder:
      "Paste the internship or role description here. Keywords will be folded into the resume draft after you click Go.",
    resumeBuilderProjectDescriptionLabel: "Projects or resume additions",
    resumeBuilderProjectDescriptionPlaceholder:
      "Describe projects, clubs, lab work, class assignments, or jobs you want included. Example: built a React site for a student org, cleaned survey data in Python, led event logistics.",
    resumeBuilderGo: "Go",
    resumeBuilderPdfViewer: "Inbuilt PDF viewer",
    resumeBuilderCopyHint: "Copy LaTeX if you want to edit the source.",
    resumeBuilderBuildingPreview: "Building PDF Preview...",
  },
  es: {
    // Home page
    homeEyebrow: "INICIO",
    homeWelcome: "¿Listo para LARP?",
    homeStartIntake: "COMENZAR",

    // Language switcher
    languageLabel: "Idioma",
    languageEnglish: "English",
    languageSpanish: "Español",

    // Telemetry banner
    telemetryAcronym: "Aprende, Aplica, Reflexiona, Progresa",

    // Stepper
    stepperPickTarget: "Elige una meta",
    stepperMapWhatYouHave: "Mapea lo que tienes",
    stepperYourWeek: "Tu semana",

    // Step 1 — role
    step1Eyebrow: "Paso 01 / Objetivo",
    step1Heading: "Elige una dirección — siempre puedes cambiarla.",
    step1Subheading:
      "Elige una. No tienes que estar seguro — solo necesitamos un punto de partida.",
    step1FreeTextLabel: "O descríbelo con tus propias palabras",
    step1FreeTextPlaceholder:
      "ej. algo donde me paguen por escribir o investigar",
    step1NoneFitButton: "Ninguna encaja — déjame describirlo",
    step1Continue: "Continuar →",

    // Step 2 — skills
    step2Eyebrow: "Paso 02 / Entradas",
    step2Heading: "¿Qué has hecho hasta ahora?",
    step2Subheading:
      "Marca lo que sea verdad. Nada todavía es una respuesta válida — el primer trimestre puede estar vacío.",
    step2Back: "← Atrás",
    step2GeneratePlan: "Generar plan →",
    quickContextLabel: "¿Algo que nos ayude a conocerte mejor?",
    contextLabel: "¿Algo más que debamos saber?",
    contextPlaceholder:
      "Opcional. Ejemplo: 'Soy estudiante de transferencia' o 'Ya tengo una pasantía, pero quiero un rol más ambicioso'",
    chipSwitchingMajors: "Estoy cambiando de carrera",
    chipTransfer: "Soy estudiante de transferencia",
    chipFirstGen: "Soy primera generación",
    chipWorkingPartTime: "Trabajo mientras estudio",

    // Skill group labels
    skillGroupCoding: "Programación",
    skillGroupDataAnalysis: "Datos y análisis",
    skillGroupDesignCreative: "Diseño y creatividad",
    skillGroupResearchLab: "Investigación y laboratorio",
    skillGroupLeadershipCommunity: "Liderazgo y comunidad",
    skillGroupWorkMoney: "Trabajo y dinero",
    skillGroupToolsMisc: "Herramientas y otros",
    skillGroupHonestAnswers: "Respuestas honestas",

    // Loading state
    loading1: "Leyendo el rol…",
    loading2: "Mapeando lo que tienes…",
    loading3: "Eligiendo movimientos en el campus con mayor impacto…",
    loading4: "Escribiendo tu semana…",

    // Plan card
    planEyebrow: "Esta semana — tu plan",
    planStartOver: "← Empezar de nuevo",
    planPrint: "Imprimir",
    planGap: "Brecha",
    planSkill: "Habilidad",
    planUnlocks: "Desbloquea",
    planDoThisWeek: "Hazlo esta semana →",
    planFooterPrefix: "Generado por L.A.R.P. con",

    // Resource type labels
    resourceTypeClub: "Club",
    resourceTypeResearch: "Investigación",
    resourceTypeWorkshop: "Taller",
    resourceTypeInternshipLite: "Pasantía ligera",
    resourceTypeIncubator: "Incubadora",
    resourceTypeProgram: "Programa",

    // Dashboard placeholder
    dashboardEyebrow: "Panel — marcador",
    dashboardHeadingPrefix: "Después del registro:",
    dashboardSubheading:
      "Área temporal del panel que tu compañero está construyendo: habilidades, generador de currículum, ubicaciones del campus y próximos pasos guardados.",
    dashboardReplaceMe: "Reemplázame",
    dashboardSkillsSnapshot: "Resumen de habilidades",
    dashboardResumeBuilder: "Generador de currículum",
    dashboardResumeBuilderDescription:
      "Marcador para los puntos generados y la exportación editable en LaTeX.",
    dashboardLocations: "Ubicaciones",
    dashboardNextSteps: "Próximos pasos",

    // Dashboard
    dashboardSectionEyebrow: "Panel",
    dashboardTopIndustrySkills: "Habilidades clave en la industria",
    dashboardSkillsRadarNeed: "Necesario",
    dashboardSkillsRadarHave: "Tú",
    dashboardResumeInputs: "Datos del currículum",
    dashboardNoChipsSelected:
      "Aún no has seleccionado nada. El generador de currículum te dará una plantilla inicial de todos modos.",

    // Resume builder
    resumeBuilderEyebrow: "Generador de currículum",
    resumeBuilderTitle: "Plantilla de currículum de Jake, prellenada",
    resumeBuilderDescription:
      "Pega una descripción de trabajo y notas de proyectos completados, luego haz clic en Listo para reescribir las palabras clave del currículum. La vista previa muestra el PDF tal como lo vería un empleador, y el LaTeX se puede copiar en Overleaf para editarlo fácilmente.",
    resumeBuilderCopyLatex: "Copiar LaTeX",
    resumeBuilderCopied: "Copiado",
    resumeBuilderDownloadPdf: "Descargar PDF",
    resumeBuilderBuildingPdf: "Generando PDF",
    resumeBuilderJobDescriptionLabel: "Descripción del trabajo",
    resumeBuilderJobDescriptionPlaceholder:
      "Pega aquí la descripción de la pasantía o el rol. Las palabras clave se incorporarán al borrador del currículum después de hacer clic en Listo.",
    resumeBuilderProjectDescriptionLabel: "Proyectos o secciones adicionales",
    resumeBuilderProjectDescriptionPlaceholder:
      "Describe proyectos, clubes, trabajo de laboratorio, tareas de clase o trabajos que quieras incluir. Ejemplo: hice un sitio en React para una organización estudiantil, limpié datos de encuestas en Python, lideré la logística de un evento.",
    resumeBuilderGo: "Listo",
    resumeBuilderPdfViewer: "Visor de PDF integrado",
    resumeBuilderCopyHint: "Copia el LaTeX si quieres editar el código fuente.",
    resumeBuilderBuildingPreview: "Generando vista previa del PDF...",
  },
} as const;

export type Language = keyof typeof translations;
export type TranslationKey = keyof typeof translations.en;

export function t(key: TranslationKey, language: Language = "en"): string {
  return translations[language][key];
}

/**
 * Map a `SkillGroup.label` (English, canonical) to its translation key.
 * Kept here so `lib/plan/skillOptions.ts` stays a plain data module.
 */
const SKILL_GROUP_LABEL_TO_KEY: Record<string, TranslationKey> = {
  Coding: "skillGroupCoding",
  "Data & analysis": "skillGroupDataAnalysis",
  "Design & creative": "skillGroupDesignCreative",
  "Research & lab": "skillGroupResearchLab",
  "Leadership & community": "skillGroupLeadershipCommunity",
  "Work & money": "skillGroupWorkMoney",
  "Tools & misc": "skillGroupToolsMisc",
  "Honest answers": "skillGroupHonestAnswers",
};

export function tSkillGroupLabel(label: string, language: Language): string {
  const key = SKILL_GROUP_LABEL_TO_KEY[label];
  return key ? t(key, language) : label;
}

const RESOURCE_TYPE_TO_KEY: Record<string, TranslationKey> = {
  club: "resourceTypeClub",
  research: "resourceTypeResearch",
  workshop: "resourceTypeWorkshop",
  "internship-lite": "resourceTypeInternshipLite",
  incubator: "resourceTypeIncubator",
  program: "resourceTypeProgram",
};

export function tResourceType(type: string, language: Language): string {
  const key = RESOURCE_TYPE_TO_KEY[type];
  return key ? t(key, language) : type;
}
